baseURL = 'https://monkeyfacts.io/'
languageCode = 'en-us'
title = 'Monkey Facts'
copyright = "© Marcin S."

paginate = 10 # articles per page
rssLimit = 20
enableRobotsTXT = false

[params]
	mode = "light" # color-mode → light,dark,toggle or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	customcss = ["css/syntax.css"]
    favicon = "/favicon.ico"
    catchphrases = ["Monkey See, Monkey Do", "We're Not Monkeying Around", "This Ain't No Monkey Business", "New Monkey Business Daily", "A Monkey Wrench In The Works"]

[permalinks]
  posts = '/:title/'

# Related Content

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'tags'
  weight = 100

# Footer links

[[params.social]]
name = "about"
icon = "user"
url = "/about"

[[params.social]]
name = "blog"
icon = "code"
url = "https://bytedude.com"

[[params.social]]
name = "email"
icon = "mail"
url = "mailto:marcin@bytedude.com"

[[params.social]]
name = "github"
icon = "github"
url = "https://github.com/m-cat"

[[params.social]]
name = "rss"
icon = "rss"
url = "/index.xml"

# Main menu Items

[[menu.main]]
name = "tags"
url = "/tags"
weight = 1

[[menu.main]]
name = "top"
url = "/top"
weight = 2

[[menu.main]]
name = "all"
url = "/posts"
weight = 3

# Other config

[markup]
  [markup.highlight]
    noClasses = false
    # lineNos = true

