baseURL = 'https://monkeyfacts.io/'
languageCode = 'en-us'
title = 'Monkey Facts'
theme = "archiebald"
copyright = "© Marcin S."

paginate = 15 # articles per page
rssLimit = 100

[params]
	mode = "light" # color-mode → light,dark,toggle or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = '"Monkey See, Monkey Do"'
	customcss = ["css/syntax.css"]

# Footer links

[[params.social]]
name = "Blog"
icon = "user"
url = "https://bytedude.com"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:marcin@bytedude.com"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/m-cat"

[[params.social]]
name = "rss"
icon = "rss"
url = "/index.xml"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Other config

[markup]
  [markup.highlight]
    noClasses = false
    # lineNos = true

