baseURL = 'https://monkeyfacts.io/'
languageCode = 'en-us'
title = 'Monkey Facts'
copyright = "© Marcin S."

paginate = 10 # articles per page
rssLimit = 20
enableRobotsTXT = false

[params]
	mode = "light" # color-mode → light,dark,toggle or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	customcss = ["css/syntax.css"]
    favicon = "/favicon.ico"
    catchphrases = ["Monkey See, Monkey Do", "We're Not Monkeying Around", "This Ain't No Monkey Business", "New Monkey Business Daily"]

[permalinks]
  posts = '/:title/'

# Related Content

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'tags'
  weight = 100

# Footer links

[[params.social]]
name = "Blog"
icon = "user"
url = "https://bytedude.com"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:marcin@bytedude.com"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/m-cat"

[[params.social]]
name = "rss"
icon = "rss"
url = "/index.xml"

# Main menu Items

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1

[[menu.main]]
name = "Top"
url = "/top"
weight = 2

[[menu.main]]
name = "All"
url = "/posts"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

# Other config

[markup]
  [markup.highlight]
    noClasses = false
    # lineNos = true

